### ISSUE TITLE
Winfetch no longer loads since 2.3.0

### ISSUE THREAD

**Issue by ghost** [jakublevy/chocopkgs#1]
Upgrade from 2.2.0 removes winfetch.ps1 which is required to run winfetch on system.

Upon running command, generates error:
The term 'C:\ProgramData\chocolatey\lib\winfetch\tools\winfetch.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.

Removing and reinstalling generates same result.

**Comment by jakublevy** [comment]
There were some problems getting Chocolatey moderators to approve winfetch package. The package structure was changed numerous time to get the package approvement. You have some left-overs on your system.

The following steps should solve your problem.
1. uninstall winfetch
`
choco uninstall winfetch
`

2. Remove directory `C:\ProgramData\chocolatey\lib\winfetch`, remove file  `C:\ProgramData\chocolatey\bin\winfetch.bat` and `C:\ProgramData\chocolatey\bin\winfetch.ps1` if present

3. install winfetch
`
choco install winfetch
`
4. reopen terminal and check that `C:\tools\winfetch` exists. This directory is added to your PATH. It should contain two files: `winfetch.ps1` and `winfetch.bat`
5. execute winfetch, it should work

The package should hopefully be stable now, and there should be no problems with future updates.

**Comment by ghost** [comment]
Yes all good. Only had to uninstall winfetch, delete C:\ProgramData\chocolatey\bin\winfetch.bat and reinstall as you suggested. Path was automatically added after installing again. All works.
