### ISSUE TITLE
Add xhs symlink to the xh package

### ISSUE THREAD

**Issue by ducaale** [jakublevy/chocopkgs#3]
`xh` maintainer here. Thank you very much for making `xh` available as a chocolatey package 😊.

I would very much appreciate it if the installation script for `xh` also installed `xhs`. This would enable users to issue HTTPS requests by default e.g `xhs httpbin.org/get`.

Also, see the following:
* https://github.com/ducaale/xh#making-https-requests-by-default
* https://github.com/ducaale/xh/blob/master/install.ps1#L46

**Comment by jakublevy** [comment]
Thanks for pointing that out, I totally missed it.
I've pushed a commit https://github.com/jakublevy/chocopkgs/commit/1998b7af3463964feebc40650a599ab94a8200d8 that copies `xh.exe` into `xhs.exe` as your script does.

It will be pushed to Chocolatey with next update.

**Comment by jakublevy** [comment]
I have pushed a fix release for version 0.15.0 to Chocolatey, see https://community.chocolatey.org/packages/xh/0.15.0.20220317
