### ISSUE TITLE
Please update sshs

### ISSUE THREAD

**Issue by Plaenkler** [jakublevy/chocopkgs#4]
SSHS is available in version 2.1.2 would be nice if the version would also be usable via choco.

**Comment by jakublevy** [comment]
2.1.x versions were pushed on 24th of February.

![](https://i.imgur.com/w0wfXQn.png)

A package must be approved by a moderator from Chocolatey before its status is changed to listed and can be installed with `choco install sshs`

If you want to install version 2.1.2, execute `choco install sshs --version 2.1.2`

**Comment by Plaenkler** [comment]
Thx worked.
